server:
  port: 8000


spring:
  application:
    name: gatewayServer

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SALONMICROSERVICE
          uri: "lb://SALONMICROSERVICE"
          predicates:
            - Path= /salon/**, /api/salon/**, /api/admin/salon/**

        - id: USERMICROSERVICE
          uri: "lb://USERMICROSERVICE"
          predicates:
            - Path= /auth/**, /api/admin/user/**, /api/user/**, /user/**

        - id: SERVICEOFFERINGMICROSERVICE
          uri:
            "lb://SERVICEOFFERINGMICROSERVICE"
          predicates:
            - Path= /api/service-offering/**

        - id: CATEGORYMICROSERVICE
          uri:
            "lb://CATEGORYMICROSERVICE"
          predicates:
            - Path= /api/category/**

        - id: BOOKINGMICROSERVICE
          uri:
            "lb://BOOKINGMICROSERVICE"
          predicates:
            - Path= /api/booking/**

        - id: PAYMENTMICROSERVICE
          uri:
            "lb://PAYMENTMICROSERVICE"
          predicates:
            - Path= /api/payment/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG

