server:
  port: 5008

spring:
  application:
    name: reviewMicroservice

  datasource:
    url: "jdbc:postgresql://localhost:5432/salon_world_review_db"
    username: postgres
    password: vivek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
