
server:
  port: 5007

spring:
  application:
    name: notificationMicroservice

  datasource:
    url: "jdbc:postgresql://localhost:5432/salon_world_notification_db"
    username: postgres
    password: vivek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
