
server:
  port: 8086

spring:
  application:
    name: paymentMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/salon_world_payment_db
    username: postgres
    password: vivek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

razorpay:
  api:
    key: rzp_test_0sX2fY2M0Mk2V1
    secret: 0sX2fY2M0Mk2V1

stripe:
  api:
    key: sk_test_51Jy8Y9Bj0Mk2V1