
server:
  port: 8081

spring:
  application:
    name: userMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/salon_world_user_db
    username: postgres
    password: vivek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
